Update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -98,7 +98,7 @@ jobs:
         run: |
           pip install pyspelling
           sudo apt-get install aspell aspell-en
-
+      
       - name: Run spell check on each file
         if: |
           steps.check-files.outputs.skip != 'true' &&
@@ -113,29 +113,33 @@ jobs:
             dictionary:
               encoding: utf-8
               wordlists:
-              - en-wordlist.txt
+              - .wordlist.txt
             pipeline:
             - pyspelling.filters.text
             sources:
             - '{{file}}'
           EOF
-          
-          # Get the list of files
+
+          # Get the list of files into an array
           if [ "${{ steps.check-files.outputs.is-pr }}" == "true" ]; then
-            FILES="${{ steps.check-files.outputs.files }}"
+            mapfile -t FILES <<< "${{ steps.check-files.outputs.files }}"
           else
-            FILES="${{ steps.push-files.outputs.files }}"
+            mapfile -t FILES <<< "${{ steps.push-files.outputs.files }}"
           fi
-          
+
           # Check each file individually
-          EXIT_CODE=0
-          echo "$FILES" | while read -r file; do
+          FINAL_EXIT_CODE=0
+          for file in "${FILES[@]}"; do
             if [ -n "$file" ]; then
               echo "Checking spelling in $file"
               sed "s|{{file}}|$file|g" .spellcheck.yml > temp_config.yml
               if ! pyspelling -c temp_config.yml; then
-                EXIT_CODE=1
+                FINAL_EXIT_CODE=1
               fi
             fi
           done
-          exit $EXIT_CODE
+
+          if [ $FINAL_EXIT_CODE -ne 0 ]; then
+            echo "Spell check failed!"
+            exit 1
+          fi
